eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      # 유레카 서버가 어디에 있는지를 위치 정보를 여기다가 명시해 둔 것이다.
      defaultZone: http://${EUREKA_SERVER_URL}:8761/eureka/

spring:
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:9200
    connection-timeout: 10s
    socket-timeout: 30s
  # jackson 설정은 spring 바로 아래로 이동
  jackson:
#    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  datasource:
    # MySQL 드라이버 지정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 도커 컨테이너로 3306 포트로 접속할 수 있도록 띄어놓은 db와 연결
    URL: jdbc:mysql://${DB_HOST}:3306/Glemoa
    username: ${DB_USERNAME} # 환경 변수로 변경
    password: ${DB_PASSWORD} # 환경 변수로 변경
  jpa:
    # 데이터 베이스 플랫폼에는 MySQL DB를 사용할 것이기 때문에 이렇게 설정
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

glemoa:
  batch-size: 100
  crawlers:
    - name: arcaLiveCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 1440
      initial-crawl-days: 30
      restart-crawl-minutes: 1440
      enabled: true
    - name: bobaedreamCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: clienCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: dcInsideCrawler
      cron: "0 */5 * * * *"  # 5분마다e
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: etolandCrawler
      cron: "0 */5 * * * *"    # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: fmkoreaCrawler
      cron: "0 */5 * * * *"  # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: humorunivCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: invenCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: mlbparkCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: natePannCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: ppomppuCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true
    - name: ruliwebCrawler
      cron: "0 */5 * * * *" # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 30
      restart-crawl-minutes: 1440
      enabled: true
    - name: theqooCrawler
      cron: "0 */5 * * * *"  # 5분마다
      lookback-minutes: 60
      initial-crawl-days: 60
      restart-crawl-minutes: 1440
      enabled: true

logging:
  config: classpath:logback-prod.xml
  level:
    # 1. 모든 외부 라이브러리 및 기본 동작은 INFO 레벨로 설정
    root: INFO
    # 2. Glemoa Reader 서비스의 핵심 로직만 DEBUG 레벨로 설정
    hyunsub.glemoa: DEBUG